# Generated by Django 5.2.17 on 2026-09-20 04:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='ended_at',
        ),
        migrations.AddField(
            model_name='experience',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
