# Generated by Django 5.2.17 on 2026-09-14 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('research', 'Research Project'), ('entrepreneurship', 'Entrepreneurship'), ('creative', 'Creative Arts'), ('organization', 'Organization Event')], default='research', max_length=30)),
                ('year', models.IntegerField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
