# Generated by Django 5.2.17 on 2026-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('organisasi', 'Organisasi'), ('kepanitiaan', 'Kepanitiaan'), ('magang', 'Magang'), ('riset', 'Riset'), ('lainnya', 'Lainnya')], default='organisasi', max_length=20),
        ),
    ]
